/// <reference types="astro/client" />
/// <reference path="../worker-configuration.d.ts" />

/**
 * Cloudflare bindings are reachable only inside a request, never at module
 * scope. `Astro.locals.runtime.env` is how every handler reaches D1 and R2.
 *
 * `Env` is generated by `npm run cf-typegen` (wrangler types) — never
 * hand-write it, or it drifts from wrangler.jsonc.
 */
type Runtime = import('@astrojs/cloudflare').Runtime<Env>;

declare namespace App {
  interface Locals extends Runtime {}
}
